/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cambio.java
 *
 * Created on 17/03/2011, 08:44:06 AM
 */

/**
 *
 * @author Administrador
 */
public class cambio extends javax.swing.JFrame {

    /** Creates new form cambio */
    public cambio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Usuario1", "Usuario2" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(90, 30, 110, 30);

        jButton1.setText("Cambiar");
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 150, 100, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 90, 130, 20);

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 150, 110, 30);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(37, 90, 70, 14);

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(34, 120, 70, 14);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(130, 120, 130, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-317)/2, (screenSize.height-239)/2, 317, 239);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
