/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * productos.java
 *
 * Created on 17/03/2011, 08:29:42 AM
 */

/**
 *
 * @author Administrador
 */
public class productos extends javax.swing.JFrame {

    /** Creates new form productos */
    public productos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jCheckBox1.setText("LCD");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(20, 30, 110, 23);

        jCheckBox2.setText("DVD");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(20, 50, 120, 23);

        jCheckBox3.setText("Plasma");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(20, 70, 120, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 30, 20, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 50, 20, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 70, 20, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 10, 180, 120);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 100, 180, 10);

        jLabel1.setText("Elementos y cantidades");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 110, 140, 14);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 160, 30, 20);

        jButton2.setText("Comprar");
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 220, 90, 23);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 90, 80);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-222)/2, (screenSize.height-297)/2, 222, 297);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
